# fly.toml app configuration file generated for whnvr on 2023-08-18T23:12:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whnvr"
primary_region = "bos"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
